apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: academic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: academic-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: academic
spec:
  selector:
    app: react-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP