apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: academic
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: academic_db
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgresql:5432/academic_db"