apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: academic
spec:
  selector:
    matchLabels:
      app: fastapi-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s